version: '3.8'

services:
  # Serviço do Frontend (Nginx)
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmd_webapp
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - jmd-network

  # Serviço do Backend (API)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: jmd_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://jmd_user:superstrongpassword123@db:5432/jmd_processos
    networks:
      - jmd-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço da Base de Dados
  db:
    image: postgres:15-alpine
    container_name: jmd_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: jmd_user
      POSTGRES_PASSWORD: superstrongpassword123
      POSTGRES_DB: jmd_processos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jmd-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jmd_user -d jmd_processos"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  jmd-network:
    driver: bridge
