version: '3.8'

services:
  # Serviço do Frontend (Nginx) que os utilizadores veem
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmd_webapp
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - jmd-network

  # Serviço do Backend (API) que fala com a base de dados
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: jmd_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Passa as credenciais para a API para que ela saiba como se conectar
      POSTGRES_USER: jmd_user
      POSTGRES_PASSWORD: superstrongpassword123
      POSTGRES_DB: jmd_processos
      DATABASE_URL: postgresql://jmd_user:superstrongpassword123@db:5432/jmd_processos
    networks:
      - jmd-network

  # Serviço da Base de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: jmd_database
    restart: unless-stopped
    environment:
      # Define as credenciais que a base de dados irá usar ao ser criada
      POSTGRES_USER: jmd_user
      POSTGRES_PASSWORD: superstrongpassword123
      POSTGRES_DB: jmd_processos
    volumes:
      # Garante que os dados da base de dados não se perdem
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jmd-network
    # Verifica se a base de dados está pronta antes de outros serviços dependerem dela
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jmd_user -d jmd_processos"]
      interval: 10s
      timeout: 5s
      retries: 5

# Define o volume para guardar os dados da base de dados
volumes:
  postgres_data:
    driver: local

# Define a rede privada para os serviços comunicarem
networks:
  jmd-network:
    driver: bridge

