version: '3.8'

services:
  # Serviço do Frontend (Nginx)
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmd_webapp
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - jmd-network

  # Serviço do Backend (API)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: jmd_api
    restart: unless-stopped
    depends_on:
      - db
    # A API agora conhece as credenciais para se identificar na base de dados
    environment:
      POSTGRES_USER: jmd_user
      POSTGRES_PASSWORD: superstrongpassword123 # Recomendo que troque esta senha
      POSTGRES_DB: jmd_processos
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - jmd-network

  # Serviço da Base de Dados
  db:
    image: postgres:15-alpine
    container_name: jmd_database
    restart: unless-stopped
    # As mesmas credenciais são usadas aqui para inicializar a base de dados
    environment:
      POSTGRES_USER: jmd_user
      POSTGRES_PASSWORD: superstrongpassword123 # Recomendo que troque esta senha
      POSTGRES_DB: jmd_processos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jmd-network

volumes:
  postgres_data:
    driver: local

networks:
  jmd-network:
    driver: bridge

